import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-page">
      <div className="max-w-3xl mx-auto px-4 py-16">
        <a
          href="/"
          className="text-[13px] text-primary hover:underline mb-8 inline-block"
        >
          &larr; Back to home
        </a>
        <h1 className="text-[28px] font-bold text-text-primary tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="text-[13px] text-text-muted mb-8 font-mono">
          Last updated: March 14, 2026
        </p>

        <div className="prose-custom">
          <Section title="1. Acceptance">
            <p>
              By creating an account or using CertBench, you agree to these
              terms. If you do not agree, do not use the service.
            </p>
          </Section>

          <Section title="2. The Service">
            <p>
              CertBench is a certification study platform that provides practice
              questions, adaptive assessments, spaced repetition, AI-powered
              question generation, and study planning tools for IT
              certifications. The service is provided &ldquo;as is&rdquo; and
              does not guarantee that you will pass any certification exam.
            </p>
          </Section>

          <Section title="3. Accounts">
            <p>
              You must provide accurate information when creating an account. You
              are responsible for maintaining the security of your account
              credentials. You must be at least 16 years old to use CertBench.
            </p>
          </Section>

          <Section title="4. Subscriptions & Billing">
            <p>
              CertBench offers a free tier and a paid Pro subscription. Pro
              subscriptions are billed monthly through Stripe. You can cancel
              your subscription at any time through the billing portal — access
              continues until the end of the current billing period. We do not
              offer refunds for partial billing periods.
            </p>
          </Section>

          <Section title="5. AI-Generated Content">
            <p>
              Questions generated by CertBench&apos;s AI are created from your
              uploaded study materials. While we employ validation to ensure
              quality, AI-generated content may contain errors. CertBench is a
              study aid and should not be your sole preparation resource. Always
              verify important information against official exam objectives and
              authoritative sources.
            </p>
          </Section>

          <Section title="6. User Content">
            <p>
              You retain ownership of study materials you upload and study sets
              you create. By making a study set public, you grant other CertBench
              users a non-exclusive licence to view and practice with that
              content. You may make any public set private at any time. You must
              not upload content that infringes on others&apos; intellectual
              property rights.
            </p>
          </Section>

          <Section title="7. Acceptable Use">
            <p>You agree not to:</p>
            <ul>
              <li>
                Use the service to distribute actual certification exam questions
                (brain dumps)
              </li>
              <li>Attempt to reverse-engineer or scrape the service</li>
              <li>
                Share your account credentials or allow others to use your
                account
              </li>
              <li>Use the AI generation feature to produce harmful or abusive content</li>
              <li>Circumvent usage limits or billing mechanisms</li>
            </ul>
          </Section>

          <Section title="8. Content Accuracy Disclaimer">
            <p>
              CertBench is not affiliated with, endorsed by, or sponsored by
              CompTIA, Amazon Web Services, Microsoft, or any other
              certification body. Certification names and exam codes are
              trademarks of their respective owners. Our practice questions are
              independently created and are not sourced from actual exam content.
            </p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>
              CertBench is provided &ldquo;as is&rdquo; without warranties of
              any kind. We are not liable for any damages arising from your use
              of the service, including but not limited to failure to pass a
              certification exam. Our total liability is limited to the amount
              you have paid us in the 12 months preceding any claim.
            </p>
          </Section>

          <Section title="10. Termination">
            <p>
              We may suspend or terminate your account if you violate these
              terms. You may delete your account at any time by contacting us.
              Upon termination, your data will be deleted in accordance with our
              Privacy Policy.
            </p>
          </Section>

          <Section title="11. Changes">
            <p>
              We may update these terms from time to time. We will notify you of
              material changes via email or an in-app notice. Continued use
              after changes constitutes acceptance.
            </p>
          </Section>

          <Section title="12. Contact">
            <p>
              Questions about these terms? Email us at{" "}
              <a
                href="mailto:certbench@proton.me"
                className="text-primary hover:underline"
              >
                certbench@proton.me
              </a>
              .
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-8">
      <h2 className="text-[17px] font-semibold text-text-primary mb-3">
        {title}
      </h2>
      <div className="text-[14px] text-text-secondary leading-relaxed space-y-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1 [&_li]:text-[14px]">
        {children}
      </div>
    </section>
  );
}
