import type {
  StudySet,
  StudyQuestion,
  MCTFOption,
  OrderingOption,
  MatchingOption,
  QuestionType,
} from "./types";
import { TYPE_LABELS } from "./types";

export async function exportPdf(
  studySet: StudySet,
  questions: StudyQuestion[]
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(studySet.title, margin, y);
  y += 8;

  if (studySet.category) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(studySet.category, margin, y);
    doc.setTextColor(0);
    y += 6;
  }

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(
    `${questions.length} questions — Generated by CertBench`,
    margin,
    y
  );
  doc.setTextColor(0);
  y += 10;

  // Questions
  questions.forEach((q, i) => {
    const qType = q.question_type || "multiple_choice";
    const typeTag =
      qType !== "multiple_choice" ? ` [${TYPE_LABELS[qType]}]` : "";

    checkPage(30);

    // Question text
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    const qLines = doc.splitTextToSize(
      `${i + 1}. ${q.question_text}${typeTag}`,
      contentWidth
    );
    doc.text(qLines, margin, y);
    y += qLines.length * 5 + 2;

    // Options
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    if (
      qType === "multiple_choice" ||
      qType === "true_false" ||
      qType === "multiple_select"
    ) {
      (q.options as MCTFOption[]).forEach((opt, optIdx) => {
        checkPage(6);
        const letter = String.fromCharCode(65 + optIdx);
        const optLines = doc.splitTextToSize(
          `   ${letter}) ${opt.text}`,
          contentWidth - 5
        );
        doc.text(optLines, margin, y);
        y += optLines.length * 4.5 + 1;
      });
    } else if (qType === "ordering") {
      (q.options as OrderingOption[]).forEach((opt, optIdx) => {
        checkPage(6);
        const optLines = doc.splitTextToSize(
          `   ${String.fromCharCode(65 + optIdx)}) ${opt.text}`,
          contentWidth - 5
        );
        doc.text(optLines, margin, y);
        y += optLines.length * 4.5 + 1;
      });
    } else if (qType === "matching") {
      (q.options as MatchingOption[]).forEach((opt, optIdx) => {
        checkPage(6);
        const optLines = doc.splitTextToSize(
          `   ${optIdx + 1}. ${opt.left}`,
          contentWidth - 5
        );
        doc.text(optLines, margin, y);
        y += optLines.length * 4.5 + 1;
      });
      y += 2;
      doc.setFont("helvetica", "italic");
      doc.text("   Definitions:", margin, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      const shuffled = [...(q.options as MatchingOption[])].sort(() =>
        Math.random() - 0.5
      );
      shuffled.forEach((opt, optIdx) => {
        checkPage(6);
        const optLines = doc.splitTextToSize(
          `   ${String.fromCharCode(65 + optIdx)}) ${opt.right}`,
          contentWidth - 5
        );
        doc.text(optLines, margin, y);
        y += optLines.length * 4.5 + 1;
      });
    }

    y += 4;
  });

  // Answer key on new page
  doc.addPage();
  y = margin;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Answer Key", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  questions.forEach((q, i) => {
    checkPage(12);
    const qType = (q.question_type || "multiple_choice") as QuestionType;
    let answer = "";

    if (qType === "multiple_choice" || qType === "true_false") {
      const correct = (q.options as MCTFOption[])[q.correct_index];
      answer = `${String.fromCharCode(65 + q.correct_index)}) ${correct?.text || ""}`;
    } else if (qType === "multiple_select") {
      const correct = (q.options as MCTFOption[])
        .map((o, idx) => (o.is_correct ? String.fromCharCode(65 + idx) : null))
        .filter(Boolean);
      answer = correct.join(", ");
    } else if (qType === "ordering") {
      const sorted = [...(q.options as OrderingOption[])].sort(
        (a, b) => a.correct_position - b.correct_position
      );
      answer = sorted.map((o) => o.text).join(" → ");
    } else if (qType === "matching") {
      answer = (q.options as MatchingOption[])
        .map((o) => `${o.left} = ${o.right}`)
        .join("; ");
    }

    doc.setFont("helvetica", "bold");
    doc.text(`${i + 1}.`, margin, y);
    doc.setFont("helvetica", "normal");
    const ansLines = doc.splitTextToSize(answer, contentWidth - 10);
    doc.text(ansLines, margin + 8, y);
    y += ansLines.length * 4.5 + 1;

    if (q.explanation) {
      doc.setTextColor(80);
      const expLines = doc.splitTextToSize(q.explanation, contentWidth - 10);
      doc.text(expLines, margin + 8, y);
      doc.setTextColor(0);
      y += expLines.length * 4 + 3;
    }
  });

  const filename = studySet.title
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .replace(/\s+/g, "-")
    .toLowerCase();
  doc.save(`${filename}.pdf`);
}
